import { readDevotionalsWithStatus } from "./devotionals";
import { buildDevotionalMemory } from "./devotional-memory";
import {
  filterPublicDevotionals,
  isPendingReview,
  normalizeDevotional,
  statusLabelHu,
} from "./devotional-status";
import {
  AUTO_GENERATE_DAILY,
  AUTO_PUBLISH_GENERATED,
  DEV_REVIEW_MODE,
  isCronGenerationEnabled,
  PROMPT_VERSION,
} from "./dev-review";
import { resolveManualGenerationTarget } from "./generation-target";
import { GEMINI_PLANNER_MODEL } from "./config";
import { getLatestDevotional, getRecentDevotionals } from "./dashboard";
import { resolveDisplayVerse, type DisplayVerse } from "./display-verse";
import { STATIC_DISPLAY_VERSE } from "./fallbacks";
import { TRUNCATED_DEVOTIONAL_REVIEW_MESSAGE } from "./devotional-text-complete";
import type { AdminDevotionalContext, AdminDevotionalListItem, Devotional } from "./types";
import type { DevotionalMemory } from "./devotional-memory";

export interface HomePageData {
  devotionals: Devotional[];
  latest: Devotional | null;
  displayVerse: DisplayVerse;
  featuredVerse: DisplayVerse;
  recent: Devotional[];
}

const EMPTY_HOME: HomePageData = {
  devotionals: [],
  latest: null,
  displayVerse: { ...STATIC_DISPLAY_VERSE },
  featuredVerse: { ...STATIC_DISPLAY_VERSE },
  recent: [],
};

export async function loadHomePageData(): Promise<HomePageData> {
  try {
    const { devotionals: all } = await readDevotionalsWithStatus();
    const devotionals = filterPublicDevotionals(all);
    const latest = getLatestDevotional(devotionals);
    const recent = getRecentDevotionals(devotionals, 3);

    const displayVerse = resolveDisplayVerse(
      devotionals,
      latest?.dayNumber ?? 1
    );

    const featuredSource =
      devotionals.find((d) => d.dayNumber === 2) ??
      devotionals.find((d) => d.dayNumber === 1) ??
      latest;

    const featuredVerse = featuredSource
      ? resolveDisplayVerse(devotionals, featuredSource.dayNumber)
      : displayVerse;

    return {
      devotionals,
      latest,
      displayVerse,
      featuredVerse,
      recent,
    };
  } catch (error) {
    console.error("[loadHomePageData]", error);
    return EMPTY_HOME;
  }
}

export async function loadSiteNavData(): Promise<{
  todayHref: string;
  publishedCount: number;
}> {
  try {
    const { devotionals: published } = await readDevotionalsWithStatus();
    const devotionals = filterPublicDevotionals(published);
    const latest = getLatestDevotional(devotionals);
    return {
      todayHref: latest ? `/nap/${latest.dayNumber}` : "/admin",
      publishedCount: devotionals.length,
    };
  } catch {
    return { todayHref: "/admin", publishedCount: 0 };
  }
}

export function buildAdminDevotionalContext(
  devotionals: Devotional[]
): AdminDevotionalContext {
  const target = resolveManualGenerationTarget(devotionals);
  const pending = devotionals
    .map(normalizeDevotional)
    .find((d) => isPendingReview(d.status));

  let reviewWarning: string | undefined;

  const truncatedPending = devotionals
    .map(normalizeDevotional)
    .find(
      (d) =>
        isPendingReview(d.status) &&
        d.lastApiError === TRUNCATED_DEVOTIONAL_REVIEW_MESSAGE
    );

  if (truncatedPending) {
    reviewWarning = TRUNCATED_DEVOTIONAL_REVIEW_MESSAGE;
  } else if (DEV_REVIEW_MODE && pending) {
    reviewWarning = `A mai áhítat még nincs jóváhagyva (${statusLabelHu(pending.status)}). Fejlesztői módban nem generálunk további napokat.`;
  }

  return {
    devReviewMode: DEV_REVIEW_MODE,
    autoGenerateDaily: AUTO_GENERATE_DAILY,
    autoPublishGenerated: AUTO_PUBLISH_GENERATED,
    cronEnabled: isCronGenerationEnabled(),
    promptVersion: PROMPT_VERSION,
    model: GEMINI_PLANNER_MODEL,
    generationTarget: {
      action: target.action,
      dayNumber: target.dayNumber,
      date: target.date,
      blockedReason: target.blockedReason,
    },
    reviewWarning,
  };
}

export function toAdminListItems(devotionals: Devotional[]): AdminDevotionalListItem[] {
  return [...devotionals]
    .map(normalizeDevotional)
    .sort((a, b) => b.dayNumber - a.dayNumber)
    .map((d) => ({
      dayNumber: d.dayNumber,
      date: d.date,
      title: d.title,
      verse: d.verse,
      status: d.status,
      generatedAt: d.generatedAt,
      updatedAt: d.updatedAt,
      editedByAdmin: d.editedByAdmin,
      category: d.category,
    }));
}

export async function loadAdminPageData(): Promise<{
  memory: DevotionalMemory;
  latest: Devotional | null;
  reviewDevotional: Devotional | null;
  adminContext: AdminDevotionalContext;
  devotionals: Devotional[];
  listItems: AdminDevotionalListItem[];
  storageError: string | null;
  storageHint: string | null;
}> {
  const {
    devotionals: raw,
    storageError,
    storageHint,
  } = await readDevotionalsWithStatus();

  if (storageError) {
    const emptyCtx = buildAdminDevotionalContext([]);
    return {
      memory: buildDevotionalMemory([]),
      latest: null,
      reviewDevotional: null,
      adminContext: emptyCtx,
      devotionals: [],
      listItems: [],
      storageError,
      storageHint,
    };
  }

  try {
    const devotionals = raw.map(normalizeDevotional);

    const reviewDevotional =
      devotionals.find((d) => isPendingReview(d.status)) ??
      getLatestDevotional(devotionals);

    const memory = buildDevotionalMemory(raw, {
      nextDayNumber: resolveManualGenerationTarget(devotionals).dayNumber,
    });

    return {
      memory,
      latest: reviewDevotional,
      reviewDevotional,
      adminContext: buildAdminDevotionalContext(devotionals),
      devotionals,
      listItems: toAdminListItems(devotionals),
      storageError: null,
      storageHint: null,
    };
  } catch (error) {
    console.error("[loadAdminPageData]", error);
    const emptyCtx = buildAdminDevotionalContext([]);
    return {
      memory: buildDevotionalMemory([]),
      latest: null,
      reviewDevotional: null,
      adminContext: emptyCtx,
      devotionals: [],
      listItems: [],
      storageError: "Nem sikerült betölteni az áhítatokat.",
      storageHint: error instanceof Error ? error.message : null,
    };
  }
}
