import { logGeminiError } from "./gemini-client";
import { toGeminiErrorDetails } from "./gemini-errors";
import { isGeminiApiError } from "./gemini-api-error";
import type { GeminiErrorDebugInfo } from "./gemini-error-labels";
import { isCronGenerationEnabled } from "./dev-review";
import { isProductionDeployment } from "./cron-env";
import { readDevotionals } from "./devotionals";
import {
  autoGenerateDailyDevotional,
  GenerationSkippedError,
} from "./generate-devotional";
import { TRUNCATED_DEVOTIONAL_REVIEW_MESSAGE } from "./devotional-text-complete";
import { getDevotionalByDate, getTodayDateIso } from "./generation-target";
import { isGeminiOverloadError } from "./gemini-overload-retry";
import { isPexelsConfigured } from "./pexels";
import { getAppTodayIso, logAppDateDebug } from "./app-date";

export type CronGenerateOutcome = "created" | "skipped" | "blocked_env" | "error";

export interface CronGenerateResult {
  outcome: CronGenerateOutcome;
  message: string;
  date: string;
  timestamp: string;
  devotional?: {
    dayNumber: number;
    date: string;
    title: string;
    status?: string;
    imageUrl?: string;
    imageSource?: string;
    pexelsPhotoId?: number;
  };
  error?: string;
  code?: string;
  hint?: string;
  debug?: GeminiErrorDebugInfo;
}

function cronLog(message: string, meta?: Record<string, unknown>): void {
  console.log(`[cron/generate-devotional] ${new Date().toISOString()} — ${message}`, meta ?? "");
}

function cronWarn(message: string, meta?: Record<string, unknown>): void {
  console.warn(`[cron/generate-devotional] ${new Date().toISOString()} — ${message}`, meta ?? "");
}

function cronError(message: string, meta?: Record<string, unknown>): void {
  console.error(`[cron/generate-devotional] ${new Date().toISOString()} — ${message}`, meta ?? "");
}

function isRetriableGenerationError(error: unknown): boolean {
  if (error instanceof GenerationSkippedError) return false;
  if (isGeminiOverloadError(error)) return true;
  const details = toGeminiErrorDetails(error);
  return (
    details.code === "GEMINI_OVERLOAD" ||
    details.code === "NETWORK" ||
    details.code === "MAX_TOKENS" ||
    details.code === "API_HTTP" ||
    details.code === "UNKNOWN"
  );
}

async function generateWithRetry(date: string) {
  try {
    return await autoGenerateDailyDevotional(date, { forcePublished: true });
  } catch (firstError) {
    if (!isRetriableGenerationError(firstError)) {
      throw firstError;
    }
    cronWarn("Gemini hiba — egy újrapróbálás", {
      error: firstError instanceof Error ? firstError.message : String(firstError),
    });
    return await autoGenerateDailyDevotional(date, { forcePublished: true });
  }
}

function logPexelsResult(devotional: {
  dayNumber: number;
  imageUrl?: string;
  imageSource?: string;
  pexelsPhotoId?: number;
}): void {
  if (devotional.imageUrl && devotional.imageSource?.startsWith("pexels")) {
    cronLog("Pexels kép sikeresen hozzárendelve", {
      dayNumber: devotional.dayNumber,
      imageSource: devotional.imageSource,
      pexelsPhotoId: devotional.pexelsPhotoId,
    });
    return;
  }

  if (isPexelsConfigured()) {
    cronWarn("Pexels: nincs megfelelő kép — fallback kép lesz a publikus oldalon", {
      dayNumber: devotional.dayNumber,
    });
  } else {
    cronWarn("Pexels: API kulcs nincs beállítva — fallback kép lesz a publikus oldalon", {
      dayNumber: devotional.dayNumber,
    });
  }
}

export async function runDailyCronGeneration(options?: {
  force?: boolean;
}): Promise<CronGenerateResult> {
  const force = options?.force === true;
  const timestamp = new Date().toISOString();
  const date = getAppTodayIso();

  logAppDateDebug("cron/generate-devotional:start", { date, force });
  cronLog("Generálás indítva", {
    date,
    appToday: getTodayDateIso(),
    force,
    vercelEnv: process.env.VERCEL_ENV ?? "local",
    nodeEnv: process.env.NODE_ENV,
  });

  if (!force && !isProductionDeployment()) {
    const message =
      "Cron generálás csak production környezetben fut (VERCEL_ENV=production). Teszthez: ?force=1";
    cronLog(message);
    return { outcome: "blocked_env", message, date, timestamp };
  }

  if (!isCronGenerationEnabled()) {
    const message = "Automatikus generálás kikapcsolva.";
    cronLog(message);
    return { outcome: "blocked_env", message, date, timestamp };
  }

  try {
    const result = await generateWithRetry(date);
    const d = result.devotional;

    logPexelsResult(d);

    const truncated = d.status === "needs_review";

    cronLog(truncated ? "Generálás kész — félbeszakadt, ellenőrzés szükséges" : "Sikeres generálás és közzététel", {
      dayNumber: d.dayNumber,
      date: d.date,
      status: d.status,
      title: d.title,
    });

    return {
      outcome: "created",
      message: truncated
        ? `A ${d.dayNumber}. nap (${d.date}) generálva — ${TRUNCATED_DEVOTIONAL_REVIEW_MESSAGE}`
        : `A ${d.dayNumber}. nap (${d.date}) sikeresen generálva és közzétéve.`,
      date,
      timestamp,
      devotional: {
        dayNumber: d.dayNumber,
        date: d.date,
        title: d.title,
        status: d.status,
        imageUrl: d.imageUrl,
        imageSource: d.imageSource,
        pexelsPhotoId: d.pexelsPhotoId,
      },
    };
  } catch (error) {
    if (error instanceof GenerationSkippedError) {
      const history = await readDevotionals();
      const existing = getDevotionalByDate(history, date);

      cronLog("Már létezik áhítat erre a napra — kihagyva (nincs felülírás)", {
        date,
        reason: error.reason,
        dayNumber: existing?.dayNumber,
        title: existing?.title,
      });

      return {
        outcome: "skipped",
        message: existing
          ? `Már van áhítat: ${existing.dayNumber}. nap — „${existing.title}”.`
          : error.reason,
        date,
        timestamp,
        devotional: existing
          ? {
              dayNumber: existing.dayNumber,
              date: existing.date,
              title: existing.title,
              status: existing.status,
              imageUrl: existing.imageUrl,
              imageSource: existing.imageSource,
              pexelsPhotoId: existing.pexelsPhotoId,
            }
          : undefined,
      };
    }

    logGeminiError(error, "cron/generate-devotional");
    const details = toGeminiErrorDetails(error);
    const apiErr =
      isGeminiApiError(error) ? error : error instanceof Error && isGeminiApiError(error.cause) ? error.cause : null;
    cronError("Gemini generálás sikertelen — előző áhítat marad aktív", {
      date,
      error: details.message,
      code: details.code,
      httpStatus: apiErr?.httpStatus,
      geminiMessage: apiErr?.geminiMessage,
      model: apiErr?.model,
      durationMs: apiErr?.durationMs,
      attempt: apiErr?.attempt,
      overloadRetry: apiErr?.overloadRetry,
    });

    return {
      outcome: "error",
      message: details.message,
      date,
      timestamp,
      error: details.message,
      code: details.code,
      hint: details.hint,
      ...(details.debug ? { debug: details.debug } : {}),
    };
  }
}
