import { getAppTodayIso } from "./app-date";
import { logGeminiError } from "./gemini-client";
import { describeErrorForLog, toGeminiErrorDetails } from "./gemini-errors";
import { readDevotionals } from "./devotionals";
import {
  autoGenerateDailyDevotional,
  GenerationSkippedError,
} from "./generate-devotional";
import { getDevotionalByDate } from "./generation-target";
import {
  MAX_AUTO_RETRIES,
  scheduleNextRetry,
} from "./generation-job-schedule";
import {
  getGenerationJob,
  saveGenerationJob,
} from "./generation-job-storage";
import {
  createEmptyGenerationJob,
  type DailyGenerationJob,
  type GenerationAttemptLogEntry,
  type GenerationJobPhase,
} from "./generation-job-types";
import { isGeminiOverloadError } from "./gemini-overload-retry";

const LOG_PREFIX = "[generation-job]";

function jobLog(message: string, meta?: Record<string, unknown>): void {
  console.log(
    `${LOG_PREFIX} ${new Date().toISOString()} — ${message}`,
    meta ?? ""
  );
}

function jobWarn(message: string, meta?: Record<string, unknown>): void {
  console.warn(
    `${LOG_PREFIX} ${new Date().toISOString()} — ${message}`,
    meta ?? ""
  );
}

function jobError(message: string, meta?: Record<string, unknown>): void {
  console.error(
    `${LOG_PREFIX} ${new Date().toISOString()} — ${message}`,
    meta ?? ""
  );
}

export function isRetriableCronGenerationError(error: unknown): boolean {
  if (error instanceof GenerationSkippedError) return false;

  if (isGeminiOverloadError(error)) return true;

  const details = toGeminiErrorDetails(error);
  return (
    details.code === "GEMINI_OVERLOAD" ||
    details.code === "NETWORK" ||
    details.code === "TIMEOUT" ||
    details.code === "QUOTA" ||
    details.code === "MAX_TOKENS" ||
    details.code === "API_HTTP" ||
    details.code === "EMPTY_RESPONSE" ||
    details.code === "DUPLICATE_VERSE" ||
    details.code === "UNKNOWN"
  );
}

function resolveAttemptPhase(job: DailyGenerationJob): GenerationJobPhase {
  if (job.retry_count === 0) return "initial";
  return "hourly";
}

function appendLog(
  job: DailyGenerationJob,
  entry: Omit<GenerationAttemptLogEntry, "attemptNumber">
): void {
  const attemptNumber = job.retry_count + 1;
  job.logs.push({ ...entry, attemptNumber });
  job.retry_count = attemptNumber;
}

async function markJobPublished(
  job: DailyGenerationJob,
  publishedAt: string
): Promise<DailyGenerationJob> {
  job.status = "published";
  job.published_at = publishedAt;
  job.next_retry_at = null;
  job.last_error = null;
  job.last_error_code = null;
  await saveGenerationJob(job);
  return job;
}

async function markJobFailed(job: DailyGenerationJob): Promise<DailyGenerationJob> {
  job.status = "failed";
  job.next_retry_at = null;
  await saveGenerationJob(job);
  return job;
}

/** Idempotens: ha már van áhítat a napra, sikernek tekintjük. */
export async function ensureDevotionalNotAlreadyPublished(
  date: string,
  job: DailyGenerationJob | null
): Promise<{ skipped: true; job: DailyGenerationJob | null } | { skipped: false }> {
  const history = await readDevotionals();
  const existing = getDevotionalByDate(history, date);

  if (!existing) {
    return { skipped: false };
  }

  jobLog("Már létezik áhítat — duplikáció elkerülve", {
    date,
    dayNumber: existing.dayNumber,
    title: existing.title,
  });

  if (job) {
    appendLog(job, {
      at: new Date().toISOString(),
      phase: resolveAttemptPhase(job),
      success: true,
      message: `Már publikálva: ${existing.dayNumber}. nap`,
    });
    await markJobPublished(
      job,
      existing.generatedAt ?? existing.updatedAt ?? new Date().toISOString()
    );
    return { skipped: true, job };
  }

  return { skipped: true, job: null };
}

export interface GenerationAttemptResult {
  success: boolean;
  skipped?: boolean;
  job: DailyGenerationJob;
  devotional?: Awaited<ReturnType<typeof autoGenerateDailyDevotional>>["devotional"];
  error?: string;
  code?: string;
}

/**
 * Egy generálási kísérlet — naplózás + job állapot frissítés.
 */
export async function runGenerationAttempt(
  date: string,
  options?: { trigger?: "cron" | "retry_processor" | "manual" }
): Promise<GenerationAttemptResult> {
  const trigger = options?.trigger ?? "cron";
  const job = (await getGenerationJob(date)) ?? createEmptyGenerationJob(date);

  const idempotent = await ensureDevotionalNotAlreadyPublished(date, job);
  if (idempotent.skipped) {
    return {
      success: true,
      skipped: true,
      job: idempotent.job ?? job,
    };
  }

  if (job.status === "failed") {
    jobWarn("Feladat FAILED állapotban — kihagyva", { date, trigger });
    return { success: false, job, error: job.last_error ?? "Sikertelen generálás." };
  }

  if (job.status === "published") {
    return { success: true, skipped: true, job };
  }

  if (
    job.status === "pending_retry" &&
    job.next_retry_at &&
    new Date(job.next_retry_at).getTime() > Date.now() &&
    trigger !== "manual"
  ) {
    jobWarn("Következő retry még nem esedékes — kihagyva", {
      date,
      next_retry_at: job.next_retry_at,
      trigger,
    });
    return {
      success: false,
      job,
      error: job.last_error ?? "Várakozás a következő automatikus újrapróbára.",
    };
  }

  if (job.auto_retry_count >= MAX_AUTO_RETRIES && job.status === "pending_retry") {
    await markJobFailed(job);
    jobError("auto_retry_count elérte a maximumot — FAILED", {
      date,
      auto_retry_count: job.auto_retry_count,
    });
    return {
      success: false,
      job,
      error: job.last_error ?? "Három óránkénti újrapróba után sem sikerült.",
    };
  }

  job.status = "running";
  job.last_attempt_at = new Date().toISOString();
  await saveGenerationJob(job);

  const phase = resolveAttemptPhase(job);
  jobLog(`Generálás indult (${trigger}, ${phase})`, {
    date,
    retry_count: job.retry_count,
    auto_retry_count: job.auto_retry_count,
    next_retry_at: job.next_retry_at,
  });

  try {
    const result = await autoGenerateDailyDevotional(date, { forcePublished: true });
    const publishedAt = new Date().toISOString();

    appendLog(job, {
      at: publishedAt,
      phase,
      success: true,
      message: `Sikeres: ${result.devotional.dayNumber}. nap — „${result.devotional.title}”`,
    });

    await markJobPublished(job, publishedAt);

    jobLog("Sikeres generálás és közzététel", {
      date,
      dayNumber: result.devotional.dayNumber,
      attempt: job.retry_count,
    });

    return {
      success: true,
      job,
      devotional: result.devotional,
    };
  } catch (error) {
    if (error instanceof GenerationSkippedError) {
      const history = await readDevotionals();
      const existing = getDevotionalByDate(history, date);
      if (existing) {
        appendLog(job, {
          at: new Date().toISOString(),
          phase,
          success: true,
          message: error.reason,
        });
        await markJobPublished(
          job,
          existing.generatedAt ?? existing.updatedAt ?? new Date().toISOString()
        );
        return { success: true, skipped: true, job, devotional: existing };
      }
    }

    const details = toGeminiErrorDetails(error);

    appendLog(job, {
      at: new Date().toISOString(),
      phase,
      success: false,
      error: details.message,
      code: details.code,
    });

    job.last_error = details.message;
    job.last_error_code = details.code;
    job.last_attempt_at = new Date().toISOString();

    logGeminiError(error, `${LOG_PREFIX} ${date}`);
    jobError("Generálási kísérlet sikertelen", {
      date,
      attempt: job.retry_count,
      ...describeErrorForLog(error),
    });

    if (!isRetriableCronGenerationError(error)) {
      await markJobFailed(job);
      jobError("Nem újrapróbálható hiba — FAILED", {
        date,
        code: details.code,
      });
      return { success: false, job, error: details.message, code: details.code };
    }

    const nextAt = scheduleNextRetry(job);
    if (!nextAt) {
      await markJobFailed(job);
      jobError("Összes óránkénti retry kimerült — FAILED", {
        date,
        auto_retry_count: job.auto_retry_count,
      });
      return { success: false, job, error: details.message, code: details.code };
    }

    job.status = "pending_retry";
    job.next_retry_at = nextAt.toISOString();
    await saveGenerationJob(job);

    jobWarn("PENDING_RETRY — következő óránkénti próba ütemezve", {
      date,
      retry_count: job.retry_count,
      auto_retry_count: job.auto_retry_count,
      next_retry_at: job.next_retry_at,
    });

    return { success: false, job, error: details.message, code: details.code };
  }
}

export type ProcessDueRetriesResult =
  | { processed: false; reason: string }
  | GenerationAttemptResult;

/**
 * Esedékes retry feladat feldolgozása (mai nap) — idempotens.
 * Hobby plan: nincs gyakori Vercel cron; admin / külső hívás vagy napi cron elején.
 */
export async function processDueGenerationRetries(
  now = new Date()
): Promise<ProcessDueRetriesResult> {
  const date = getAppTodayIso(now);
  const job = await getGenerationJob(date);

  if (!job) {
    return { processed: false, reason: "Nincs aktív feladat a mai napra." };
  }

  const idempotent = await ensureDevotionalNotAlreadyPublished(date, job);
  if (idempotent.skipped) {
    return {
      success: true,
      skipped: true,
      job: idempotent.job ?? job,
    };
  }

  if (job.status === "published") {
    return { processed: false, reason: "A mai generálás már sikeres." };
  }

  if (job.status === "failed") {
    return { processed: false, reason: "A mai generálás véglegesen sikertelen (FAILED)." };
  }

  if (job.status !== "pending_retry") {
    return { processed: false, reason: "Nincs függőben lévő retry (pending_retry)." };
  }

  if (job.auto_retry_count >= MAX_AUTO_RETRIES) {
    await markJobFailed(job);
    return {
      processed: false,
      reason: `Elértük a maximum ${MAX_AUTO_RETRIES} óránkénti újrapróbát — FAILED.`,
    };
  }

  if (!job.next_retry_at) {
    return { processed: false, reason: "Hiányzó next_retry_at." };
  }

  if (new Date(job.next_retry_at).getTime() > now.getTime()) {
    return {
      processed: false,
      reason: `Következő retry: ${job.next_retry_at}`,
    };
  }

  jobLog("Ütemezett óránkénti retry indítása", {
    date,
    retry_count: job.retry_count,
    auto_retry_count: job.auto_retry_count,
    next_retry_at: job.next_retry_at,
  });

  return runGenerationAttempt(date, { trigger: "retry_processor" });
}
