export type DevotionalStatus =
  | "draft"
  | "needs_review"
  | "approved"
  | "published";

/** Korábbi verzió pillanatkép (újragenerálás / AI finomítás backup) */
export interface DevotionalVersionSnapshot {
  savedAt: string;
  reason: "regenerate" | "manual_backup" | "ai_iteration";
  /** AI finomítás: admin instrukció */
  instruction?: string;
  title: string;
  verse: string;
  content: string;
  prayer?: string;
  reflectionQuestion?: string;
  facebookCopy?: string;
  status?: string;
  promptVersion?: string;
}

export interface Devotional {
  dayNumber: number;
  /** Naptári nap (YYYY-MM-DD) */
  date: string;
  title: string;
  verse: string;
  content: string;
  prayer?: string;
  reflectionQuestion?: string;
  /** Napi áhítat illusztráció URL — üres, ha nincs hozzárendelve (Pexels / feltöltött) */
  imageUrl: string;
  /** Gemini által javasolt angol kulcsszavak Pexels kereséshez */
  imageKeywords?: string;
  /** Kép forrása: pexels_auto | pexels | manual | imagen */
  imageSource?: "pexels_auto" | "pexels" | "imagen" | "manual";
  /** Fotós neve / attribution (Pexels) */
  imageCredit?: string;
  imagePhotographerUrl?: string;
  pexelsPhotoId?: number;
  createdAt: string;
  generatedAt?: string;
  updatedAt?: string;
  status?: DevotionalStatus;
  promptVersion?: string;
  generationModel?: string;
  contentCharCount?: number;
  lastApiError?: string;
  editedByAdmin?: boolean;
  versionHistory?: DevotionalVersionSnapshot[];
  category?: string;
  facebookCopy?: string;
}

export interface GenerateRequestBody {
  dayNumber: number;
  verseText: string;
}

export interface GeneratedDevotionalContent {
  title: string;
  content: string;
}

/** Gemini dinamikus tervező teljes nap válasza */
export interface DynamicPlannedDay {
  dayNumber: number;
  title: string;
  verse: string;
  content: string;
  category: string;
  /** Rövid kivonat — Facebook megosztáshoz */
  excerpt?: string;
  facebookCopy?: string;
  imageKeywords?: string;
  /** false = félbeszakadt / hiányos — ne published */
  textComplete?: boolean;
  generationReviewMessage?: string;
  generationDiagnostics?: {
    sourceFunction: string;
    maxOutputTokens: number;
    finishReason: string;
    devotionalMarkdownLength: number;
    meditationLength: number;
    retryOccurred: boolean;
  };
}

/** Gemini AI finomítás preview / apply payload */
export interface DevotionalRefinementResult {
  title: string;
  verse: string;
  category: string;
  content: string;
  prayer?: string;
  reflectionQuestion?: string;
  facebookCopy?: string;
  imageKeywords?: string;
}

export interface AdminDevotionalContext {
  devReviewMode: boolean;
  autoGenerateDaily: boolean;
  autoPublishGenerated: boolean;
  cronEnabled: boolean;
  promptVersion: string;
  model: string;
  generationTarget: {
    action: string;
    dayNumber: number;
    date: string;
    blockedReason?: string;
  };
  reviewWarning?: string;
}

export interface AdminDevotionalListItem {
  dayNumber: number;
  date: string;
  title: string;
  verse: string;
  status: DevotionalStatus;
  generatedAt?: string;
  updatedAt?: string;
  editedByAdmin?: boolean;
  category?: string;
}
