import { NextRequest, NextResponse } from "next/server";
import { isAuthorizedCronRequest } from "@/lib/cron-auth";
import { logGeminiError } from "@/lib/gemini-client";
import { toGeminiErrorDetails } from "@/lib/gemini-errors";
import { isCronGenerationEnabled } from "@/lib/dev-review";
import {
  autoGenerateDailyDevotional,
  GenerationSkippedError,
} from "@/lib/generate-devotional";

export const maxDuration = 300;
export const dynamic = "force-dynamic";

async function handleCron(request: NextRequest) {
  if (!isAuthorizedCronRequest(request)) {
    return NextResponse.json(
      { error: "Érvénytelen vagy hiányzó CRON_SECRET." },
      { status: 401 }
    );
  }

  if (!process.env.CRON_SECRET) {
    return NextResponse.json(
      { error: "CRON_SECRET nincs beállítva a környezeti változók között." },
      { status: 500 }
    );
  }

  if (!isCronGenerationEnabled()) {
    return NextResponse.json(
      {
        skipped: true,
        message: "Automatikus generálás kikapcsolva (AUTO_GENERATE_DAILY=false).",
      },
      { status: 200 }
    );
  }

  try {
    const result = await autoGenerateDailyDevotional();
    const devotional = result.devotional;

    return NextResponse.json({
      success: true,
      message: `A ${devotional.dayNumber}. nap (${devotional.date}) sikeresen generálva.`,
      devotional: {
        dayNumber: devotional.dayNumber,
        date: devotional.date,
        title: devotional.title,
        status: devotional.status,
      },
    });
  } catch (err) {
    if (err instanceof GenerationSkippedError) {
      return NextResponse.json({
        skipped: true,
        message: err.reason,
      });
    }

    logGeminiError(err, "GET/POST /api/cron/generate-daily");
    const details = toGeminiErrorDetails(err);
    return NextResponse.json(
      { error: details.message, code: details.code, hint: details.hint },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  return handleCron(request);
}

export async function POST(request: NextRequest) {
  return handleCron(request);
}
